// Kullanıcı renk paleti
export const colorPalette = [
  { id: 'blue', name: 'Mavi', bg: 'bg-blue-500', darkBg: 'dark:bg-blue-600' },
  { id: 'amber', name: 'Turuncu', bg: 'bg-amber-500', darkBg: 'dark:bg-amber-600' },
  { id: 'emerald', name: 'Yeşil', bg: 'bg-emerald-500', darkBg: 'dark:bg-emerald-600' },
  { id: 'rose', name: 'Kırmızı', bg: 'bg-rose-500', darkBg: 'dark:bg-rose-600' },
  { id: 'purple', name: 'Mor', bg: 'bg-purple-500', darkBg: 'dark:bg-purple-600' },
  { id: 'pink', name: 'Pembe', bg: 'bg-pink-500', darkBg: 'dark:bg-pink-600' },
  { id: 'cyan', name: 'Cyan', bg: 'bg-cyan-500', darkBg: 'dark:bg-cyan-600' },
  { id: 'indigo', name: 'İndigo', bg: 'bg-indigo-500', darkBg: 'dark:bg-indigo-600' },
  { id: 'zinc', name: 'Gri', bg: 'bg-zinc-500', darkBg: 'dark:bg-zinc-600' },
];

// Renk teması varyantları
export const colorVariants = {
  zinc: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-zinc-500 dark:bg-zinc-600",
    border: "border-zinc-200 dark:border-zinc-700",
    hoverBorder: "hover:border-zinc-300 dark:hover:border-zinc-600",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-zinc-400/30 dark:text-zinc-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  },
  blue: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-blue-500 dark:bg-blue-600",
    border: "border-blue-300 dark:border-blue-600/50",
    hoverBorder: "hover:border-blue-500 dark:hover:border-blue-400",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-blue-400/30 dark:text-blue-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  },
  amber: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-amber-500 dark:bg-amber-600",
    border: "border-amber-300 dark:border-amber-600/50",
    hoverBorder: "hover:border-amber-500 dark:hover:border-amber-400",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-amber-400/30 dark:text-amber-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  },
  emerald: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-emerald-500 dark:bg-emerald-600",
    border: "border-emerald-300 dark:border-emerald-600/50",
    hoverBorder: "hover:border-emerald-500 dark:hover:border-emerald-400",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-emerald-400/30 dark:text-emerald-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  },
  rose: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-rose-500 dark:bg-rose-600",
    border: "border-rose-300 dark:border-rose-600/50",
    hoverBorder: "hover:border-rose-500 dark:hover:border-rose-400",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-rose-400/30 dark:text-rose-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  },
  purple: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-purple-500 dark:bg-purple-600",
    border: "border-purple-300 dark:border-purple-600/50",
    hoverBorder: "hover:border-purple-500 dark:hover:border-purple-400",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-purple-400/30 dark:text-purple-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  },
  pink: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-pink-500 dark:bg-pink-600",
    border: "border-pink-300 dark:border-pink-600/50",
    hoverBorder: "hover:border-pink-500 dark:hover:border-pink-400",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-pink-400/30 dark:text-pink-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  },
  cyan: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-cyan-500 dark:bg-cyan-600",
    border: "border-cyan-300 dark:border-cyan-600/50",
    hoverBorder: "hover:border-cyan-500 dark:hover:border-cyan-400",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-cyan-400/30 dark:text-cyan-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  },
  indigo: {
    bg: "bg-zinc-50 dark:bg-zinc-900/70",
    headerBg: "bg-indigo-500 dark:bg-indigo-600",
    border: "border-indigo-300 dark:border-indigo-600/50",
    hoverBorder: "hover:border-indigo-500 dark:hover:border-indigo-400",
    text: "text-white dark:text-white",
    accent: "bg-white/20 text-white dark:bg-indigo-400/30 dark:text-indigo-100",
    buttonHover: "hover:bg-white/20 dark:hover:bg-white/10",
  }
};